import React, { useState, useEffect, useRef } from 'react';
import { Routes, Route, Navigate, useLocation, useNavigate } from 'react-router-dom';
import Header from './components/Header';
import Sidebar from './components/Sidebar';

// Auth View
import Login from './views/auth/Login';

// Admin Views
import AdminDashboard from './views/admin/AdminDashboard';
import AdminGrants from './views/admin/AdminGrants';
import AdminAudit from './views/admin/AdminAudit';
import AdminSubAdmins from './views/admin/AdminSubAdmins';
import AdminPolicy from './views/admin/AdminPolicy';
import AdminPublic from './views/admin/AdminPublic';
import AdvancedFeatures from './views/admin/AdvancedFeatures';

// Sub-Admin Views
import SubZoneMonitor from './views/sub/SubZoneMonitor';
import SubAlerts from './views/sub/SubAlerts';
import SubVerification from './views/sub/SubVerification';
import SubZoneReports from './views/sub/SubZoneReports';

// Manager Views
import ManagerDashboard from './views/manager/ManagerDashboard';
import ManagerCCTV from './views/manager/ManagerCCTV';
import ManagerGateRFID from './views/manager/ManagerGateRFID';
import ManagerFeedStock from './views/manager/ManagerFeedStock';
import ManagerHealth from './views/manager/ManagerHealth';
import ManagerPerimeter from './views/manager/ManagerPerimeter';

// Modals
import GrantApprovalModal from './components/Modals/GrantApprovalModal';
import PhotoProofModal from './components/Modals/PhotoProofModal';
import AuditReportModal from './components/Modals/AuditReportModal';
import AddHealthModal from './components/Modals/AddHealthModal';
import AddSubAdminModal from './components/Modals/AddSubAdminModal';
import AddCowModal from './components/Modals/AddCowModal';

// Data & Sound
import {
  INITIAL_GAUSHALAS,
  INITIAL_ALERTS,
  SUB_ADMINS_LIST,
  VET_HEALTH_RECORDS
} from './data/portalData';
import { playNotificationSound, playAlertWarningSound } from './sound';
import { useLanguage } from './context/LanguageContext';

const NEW_TICKER_ALERTS = [
  {
    type: 'warning',
    titleHi: 'अनधिकृत वाहन प्रवेश – ANPR मिलान विफल',
    titleEn: 'Unauthorized Vehicle Entry – ANPR Mismatch',
    descHi: 'गोपाल गौशाला, दुर्ग गेट नं. 2',
    descEn: 'Gopal Gaushala, Durg Gate No. 2'
  },
  {
    type: 'info',
    titleHi: 'चारा स्टॉक 30% से नीचे – बस्तर',
    titleEn: 'Fodder Stock Below 30% – Bastar',
    descHi: 'AI Ration Engine द्वारा स्वतः इंडेंट',
    descEn: 'Auto indent generated by AI Ration Engine'
  },
  {
    type: 'info',
    titleHi: 'नई हेडकाउंट गणना सत्यापित – 233/240',
    titleEn: 'New Headcount Verified – 233/240',
    descHi: 'दुर्ग गौशाला · Auto Edge-Headcount',
    descEn: 'Durg Gaushala · Auto Edge-Headcount'
  },
  {
    type: 'critical',
    titleHi: 'बीमार गाय पहचानी गई – Tag IN9820-5512',
    titleEn: 'Sick Cow Detected – Tag IN9820-5512',
    descHi: 'आरंग · Shed-C (लंगड़ापन पहचान)',
    descEn: 'Arang · Shed-C (Lameness detection)'
  },
];

export default function App() {
  const { isHi } = useLanguage();
  const location = useLocation();
  const navigate = useNavigate();

  // Auth State
  const [isAuthenticated, setIsAuthenticated] = useState(!!localStorage.getItem('token'));
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('user') || 'null'));
  const [role, setRole] = useState(user?.role ? (user.role === 'ADMIN' ? 'admin' : (user.role === 'SUB_ADMIN' ? 'sub' : 'mgr')) : 'admin');
  
  const [theme, setTheme] = useState('light');
  const [soundEnabled, setSoundEnabled] = useState(true);

  // Core Data States
  const [gaushalas, setGaushalas] = useState(INITIAL_GAUSHALAS);
  const [alerts, setAlerts] = useState(INITIAL_ALERTS);
  const [subAdmins, setSubAdmins] = useState(SUB_ADMINS_LIST);
  const [healthRecords, setHealthRecords] = useState(VET_HEALTH_RECORDS);
  const [stock, setStock] = useState({ hara: 4200, sukha: 1500, dana: 380 });

  const [grants, setGrants] = useState(() => [
    { g: INITIAL_GAUSHALAS[0], amt: '₹ 6.12 L', st: 'pending' },
    { g: INITIAL_GAUSHALAS[1], amt: '₹ 5.40 L', st: 'pending' },
    { g: INITIAL_GAUSHALAS[4], amt: '₹ 4.50 L', st: 'pending' },
    { g: INITIAL_GAUSHALAS[3], amt: '₹ 7.00 L', st: 'approved' },
  ]);

  // Toast Notification State
  const [toastMsg, setToastMsg] = useState('');
  const toastTimer = useRef(null);

  const showToast = (msg) => {
    setToastMsg(msg);
    clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => {
      setToastMsg('');
    }, 3200);
  };

  // Modals state
  const [grantModalItem, setGrantModalItem] = useState(null);
  const [photoProofData, setPhotoProofData] = useState(null);
  const [auditModalData, setAuditModalData] = useState(null);
  const [adoptionCow, setAdoptionCow] = useState(null);
  const [addHealthModalOpen, setAddHealthModalOpen] = useState(false);
  const [addSubAdminModalOpen, setAddSubAdminModalOpen] = useState(false);
  const [addCowModalOpen, setAddCowModalOpen] = useState(false);

  // Sync auth state
  useEffect(() => {
    const token = localStorage.getItem('token');
    const storedUser = JSON.parse(localStorage.getItem('user'));
    setIsAuthenticated(!!token);
    if (storedUser) {
      setUser(storedUser);
      setRole(storedUser.role === 'ADMIN' ? 'admin' : (storedUser.role === 'SUB_ADMIN' ? 'sub' : 'mgr'));
    }
  }, [location.pathname]);

  const handleRoleChange = (newRole) => {
    setRole(newRole);
    if (newRole === 'admin') navigate('/admin/dashboard');
    else if (newRole === 'sub') navigate('/sub/zone');
    else if (newRole === 'mgr') navigate('/manager/dashboard');
  };

  // Background Live Alert simulation
  const tickerIdx = useRef(0);
  useEffect(() => {
    // Fake AI Alert Simulation (Only runs if VITE_DEMO_MODE is true in .env)
    if (import.meta.env.VITE_DEMO_MODE !== 'true') return;

    const interval = setInterval(() => {
      const template = NEW_TICKER_ALERTS[tickerIdx.current % NEW_TICKER_ALERTS.length];
      tickerIdx.current++;

      const newAlert = {
        id: 'ALT-' + Math.floor(200 + Math.random() * 800),
        type: template.type,
        title: isHi ? template.titleHi : template.titleEn,
        titleHi: template.titleHi,
        titleEn: template.titleEn,
        desc: isHi ? template.descHi : template.descEn,
        descHi: template.descHi,
        descEn: template.descEn,
        time: new Date().toLocaleTimeString(isHi ? 'hi-IN' : 'en-US', { hour: '2-digit', minute: '2-digit' }),
        status: 'pending'
      };

      setAlerts((prev) => [newAlert, ...prev].slice(0, 15));
      showToast(isHi ? `🔔 नया AI अलर्ट: ${template.titleHi}` : `🔔 New AI Alert: ${template.titleEn}`);
      if (soundEnabled) {
        if (template.type === 'critical') playAlertWarningSound();
        else playNotificationSound();
      }
    }, 16000);

    return () => clearInterval(interval);
  }, [soundEnabled, isHi]);

  // Stock deduction / addition
  const handleDeductStock = (cows) => {
    setStock((prev) => ({
      hara: Math.max(0, prev.hara - cows * 15),
      sukha: Math.max(0, prev.sukha - cows * 5),
      dana: Math.max(0, prev.dana - cows * 1.5),
    }));
    showToast(isHi ? `✓ ${cows} गायों के राशन अनुसार गोदाम स्टॉक से स्वतः कटौती की गई` : `✓ Auto-deducted warehouse stock for ${cows} cows ration`);
  };

  const handleAddStock = (itemKey, amount) => {
    setStock((prev) => ({
      ...prev,
      [itemKey]: prev[itemKey] + amount
    }));
  };

  const handleConfirmGrant = (index, status, txnId) => {
    setGrants((prev) => prev.map((g, idx) => idx === index ? { ...g, st: status, txnId } : g));
    showToast(status === 'स्वीकृत' || status === 'Approved' ? (isHi ? `✓ DBT अनुदान स्वीकृत! सं. ${txnId || ''}` : `✓ DBT Grant Approved! Ref: ${txnId || ''}`) : (isHi ? 'अनुदान रोका गया' : 'Grant Withheld'));
  };

  const handleRejectGrant = (index) => {
    setGrants((prev) => prev.map((g, idx) => idx === index ? { ...g, st: isHi ? 'रोका गया' : 'Held' } : g));
    showToast(isHi ? 'अनुदान रोका गया – भौतिक निरीक्षण अनुशंसित' : 'Grant Withheld – On-site inspection recommended');
  };

  return (
    <Routes>
      <Route path="/login" element={<Login />} />
      <Route path="*" element={
        !isAuthenticated ? (
          <Navigate to="/login" replace />
        ) : (
          <div className="portal-container" data-theme={theme}>
            <Header
              role={role}
              onRoleChange={handleRoleChange}
              theme={theme}
              onThemeToggle={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
              soundEnabled={soundEnabled}
              onSoundToggle={() => {
                const next = !soundEnabled;
                setSoundEnabled(next);
                showToast(next ? (isHi ? '🔊 ध्वनि चालू (Audio On)' : '🔊 Audio Enabled') : (isHi ? '🔇 ध्वनि म्यूट (Audio Muted)' : '🔇 Audio Muted'));
              }}
              alerts={alerts}
              onAlertClick={(alertItem) => showToast(isHi ? `अलर्ट: ${alertItem.titleHi || alertItem.title}` : `Alert: ${alertItem.titleEn || alertItem.title}`)}
            />

            <div className="portal-body">
              <Sidebar role={role} />

              <main className="portal-main">
                <Routes>
                  {/* Admin Routes */}
                  <Route path="/admin/dashboard" element={<AdminDashboard gaushalas={gaushalas} alerts={alerts} onOpenAuditModal={setAuditModalData} onOpenGrantModal={setGrantModalItem} onNavigateTab={(p) => navigate('/admin/' + p)} />} />
                  <Route path="/admin/grants" element={<AdminGrants grants={grants} onOpenGrantModal={setGrantModalItem} onRejectGrant={handleRejectGrant} />} />
                  <Route path="/admin/audit" element={<AdminAudit gaushalas={gaushalas} onOpenAuditModal={setAuditModalData} />} />
                  <Route path="/admin/sub-admins" element={<AdminSubAdmins subAdmins={subAdmins} onOpenAddModal={() => setAddSubAdminModalOpen(true)} />} />
                  <Route path="/admin/policy" element={<AdminPolicy onShowToast={showToast} />} />
                  <Route path="/admin/public" element={<AdminPublic onOpenPhotoModal={setPhotoProofData} onShowToast={showToast} />} />
                  <Route path="/admin/ai-features" element={<AdvancedFeatures onShowToast={showToast} />} />

                  {/* Sub-Admin Routes */}
                  <Route path="/sub/zone" element={<SubZoneMonitor gaushalas={gaushalas} onOpenPhotoModal={setPhotoProofData} onShowToast={showToast} />} />
                  <Route path="/sub/alerts" element={<SubAlerts alerts={alerts} onShowToast={showToast} onUpdateAlertStatus={(id, status, action) => setAlerts(prev => prev.map(a => a.id === id ? { ...a, status, actionTaken: action } : a))} />} />
                  <Route path="/sub/verify" element={<SubVerification gaushalas={gaushalas} onOpenPhotoModal={setPhotoProofData} onShowToast={showToast} />} />
                  <Route path="/sub/reports" element={<SubZoneReports onShowToast={showToast} />} />

                  {/* Manager Routes */}
                  <Route path="/manager/dashboard" element={<ManagerDashboard alerts={alerts} stock={stock} onNavigateTab={(p) => navigate('/manager/' + p)} onOpenAddCowModal={() => setAddCowModalOpen(true)} />} />
                  <Route path="/manager/cctv" element={<ManagerCCTV onOpenPhotoModal={setPhotoProofData} onShowToast={showToast} />} />
                  <Route path="/manager/gate" element={<ManagerGateRFID onOpenPhotoModal={setPhotoProofData} onShowToast={showToast} />} />
                  <Route path="/manager/feed" element={<ManagerFeedStock stock={stock} onDeductStock={handleDeductStock} onAddStock={handleAddStock} onShowToast={showToast} />} />
                  <Route path="/manager/health" element={<ManagerHealth healthRecords={healthRecords} onOpenAddHealthModal={() => setAddHealthModalOpen(true)} />} />
                  <Route path="/manager/perimeter" element={<ManagerPerimeter onShowToast={showToast} />} />

                  <Route path="*" element={<Navigate to={role === 'admin' ? '/admin/dashboard' : (role === 'sub' ? '/sub/zone' : '/manager/dashboard')} replace />} />
                </Routes>
              </main>
            </div>

            {/* Global Toast Notification */}
            {toastMsg && <div className="portal-toast">{toastMsg}</div>}

            {/* Modals Container */}
            {grantModalItem && <GrantApprovalModal grantItem={grantModalItem} onClose={() => setGrantModalItem(null)} onConfirm={handleConfirmGrant} />}
            {photoProofData && <PhotoProofModal proofData={photoProofData} onClose={() => setPhotoProofData(null)} />}
            {auditModalData && <AuditReportModal auditData={auditModalData} onClose={() => setAuditModalData(null)} />}
            {addHealthModalOpen && <AddHealthModal onClose={() => setAddHealthModalOpen(false)} onAddRecord={(rec) => { setHealthRecords(prev => [rec, ...prev]); showToast(isHi ? `✓ नया स्वास्थ्य रिकॉर्ड दर्ज: ${rec.cowName} (${rec.tag})` : `✓ New veterinary record logged: ${rec.cowName} (${rec.tag})`); }} />}
            {addSubAdminModalOpen && <AddSubAdminModal onClose={() => setAddSubAdminModalOpen(false)} onAddOfficer={(officer) => { setSubAdmins(prev => [...prev, officer]); showToast(isHi ? `✓ नया उप-प्रशासक असाइन किया गया: ${officer.name} (${officer.zone})` : `✓ New Sub-Admin assigned: ${officer.name} (${officer.zone})`); }} />}
            {addCowModalOpen && <AddCowModal onClose={() => setAddCowModalOpen(false)} onAddCow={(cow) => { setGaushalas(prev => prev.map((g, i) => i === 0 ? { ...g, reg: g.reg + 1, ver: g.ver + 1 } : g)); showToast(isHi ? `✓ नया गोवंश (${cow.tag}) गौशाला में सफलतापूर्वक पंजीकृत किया गया।` : `✓ New cattle (${cow.tag}) registered successfully in shelter.`); }} />}
          </div>
        )
      } />
    </Routes>
  );
}
